### ISSUE TITLE
Lockwise does not report FXA authentication errors

### ISSUE THREAD

**Issue by lnicola** [mozilla-lockwise/lockwise-android#1107]
My Lockwise does not sync anymore. If I pull to refresh, it just sits there with the spinner thing spinning, and never finishes. I do have a relatively large number of logins (437 according to Firefox). Sync works in Firefox Desktop.

I'll try to clear the app data, but is there something else (like `adb logcat`) I should try before doing that to help debug the issue?

### Device & build information
* Device: OnePlus 6T
* Build version: 3.2.0

**Comment by lnicola** [comment]
I don't see any errors when pulling to refresh, but I do have this from before:

```
12-09 18:14:17.730 31774 31816 W fxa_client::ffi: Unexpected error: Error(
12-09 18:14:17.730 31774 31816 W fxa_client::ffi: 
12-09 18:14:17.730 31774 31816 W fxa_client::ffi: Remote server error: '400' '108' 'Bad Request' 'Invalid token' 'https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors')
12-09 18:14:17.730 31774 31816 E FirefoxAccount: Error while running: getProfile
12-09 18:14:17.730 31774 31816 E FirefoxAccount: c.c.b.d$d: Remote server error: '400' '108' 'Bad Request' 'Invalid token' 'https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors'
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at c.c.b.o.b.intoException(RustError.kt:4)
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at c.c.b.c.a(FirefoxAccount.kt:39)
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at c.b.a.a.g$b.invoke(FirefoxAccount.kt:3)
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at h.a.a.a.v0.l.v0.a(TypeWithEnhancement.kt:75)
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at c.b.a.a.g.c(FirefoxAccount.kt:5)
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at h.y.i.a.a.b(ContinuationImpl.kt:2)
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at i.a.m0.run(Dispatched.kt:15)
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at i.a.b2.b.a(CoroutineScheduler.kt:74)
12-09 18:14:17.730 31774 31816 E FirefoxAccount: 	at i.a.b2.b$a.run(CoroutineScheduler.kt:45)
12-09 18:14:17.730 31774 31844 D fxaclient_ffi: fxa_get_access_token
```

**Comment by eliserichards** [comment]
Thanks for reporting this @lnicola! 
Marking this as related to #770

**Comment by lnicola** [comment]
@eliserichards ugh, this is exactly like https://github.com/mozilla-lockwise/lockwise-android/issues/753#issuecomment-553553337. The first launch after logging back in went fine, but now I'm stuck on the splash screen.

Closing as a duplicate of #753.
