### ISSUE TITLE
Unlocking prevented after deleting settings security option

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#702]
1. Install and launch lockwise.
2. Login with valid credentials.
3. Reach settings and set for example a **`Pin code`** as security option.
4. Lock lockwise and close the app.
5. Reach the device security settings and delete the **`Pin code`** as security option.
6. Launch lockwise and try to unlock it.

### Expected behavior
Once the device security option is deleted, lockwise should remove it too and let the user to access the app.
### Actual behavior
Lockwise is stuck and cannot be unlocked anymore.
### Device and build information
* **`Google Pixel 3(Android 9)`**
*  **`Lockbox version: 1.1.0 (3951)`**
### Notes
Note that if for example the pin code was `0000` and deleting it from phone settings, after adding any other pin code for example `9999` it will unlock lockwise no matter what pin code was before.
For more details please see the attachments: [video](https://drive.google.com/open?id=1LS0exU79_I5VcrkY7k9oCpO4_i8zNpzB) and [logcat.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3216962/logcat.txt)

**Comment by abodea** [comment]
<details>
<summary>Here is the exact error that was displayed when I tapped on the `Unlock` button:</summary>
2019-05-24 15:57:44.332 12925-12925/? E/Lockwise: Unlock fallback failed: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1666)
        at android.app.Activity.startActivityForResult(Activity.java:4586)
        at b.m.a.i.startActivityForResult(FragmentActivity.java:6)
        at b.h.a.a.a(ActivityCompat.java:2)
        at b.m.a.i.a(FragmentActivity.java:10)
        at androidx.fragment.app.Fragment.a(Fragment.java:28)
        at androidx.fragment.app.Fragment.a(Fragment.java:25)
        at h.c.g.Ib.a(RoutePresenter.kt:57)
        at h.c.g.v.a(AppRoutePresenter.kt:46)
        at h.c.g.p.a(AppRoutePresenter.kt:3)
        at h.c.g.q.accept(Unknown Source:2)
        at d.a.e.d.g.a(LambdaObserver.java:7)
        at d.a.e.e.b.q$a.run(ObservableObserveOn.java:23)
        at d.a.a.b.c$b.run(HandlerScheduler.java:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
</details>

**Comment by devinreams** [comment]
>if for example the pin code was 0000 and deleting it from phone settings, after adding any other pin code for example 9999 it will unlock lockwise no matter what pin code was before

Thanks for going beyond and testing this, that's useful to know as a workaround.

**Comment by sashei** [comment]
I'm working on this now; I think that it's expected behavior that we will accept any device security when unlocking (as opposed to forcing users to sign in again when they change their PIN, pattern, or fingerprints).
