### ISSUE TITLE
Lockwise crashes when turning the internet connection on and refreshing the Entries list with the Error Handling

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#861]
## Steps to reproduce
1. Launch Lockwise.
2. Login with valid credentials.
3. Reach the entries screen.
4. Turn off the Internet connection.
5. Close Lockwise.
6. Turn on the internet connection.
7. Launch Lockwise and swipe down to refresh the entries menu.
### Expected behavior
The entries list is refreshed.
### Actual behavior
Lockwise crashes when refreshing the entries list.
### Device & build information
* Device: **`Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 9 and 8), Samsung Galaxy S7(Android 7)`**
* Build version: **`1.1.3 (Build 4584)`**
### Notes
Attachments: 
[Video](https://drive.google.com/file/d/1hfzgFngETtFqHJRK0XfqnN-YXJ_SMrxc/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3442259/logcat.txt)

**Comment by abodea** [comment]
Please note that a the beginning of the crash this URL was present https://github.com/ReactiveX/RxJava/wiki/Error-Handling 
```css
  --------- beginning of crash
2019-07-29 15:40:45.723 29338-29338/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mozilla.lockbox, PID: 29338
    d.a.c.b: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | null
        at d.a.e.b.a$l.accept(Functions.java:2)
        at d.a.e.d.g.a(LambdaObserver.java:13)
        at d.a.e.d.g.a(LambdaObserver.java:10)
        at d.a.e.e.b.p$a.a(ObservableMap.java:5)
        at d.a.e.e.b.j$a.a(ObservableFilter.java:3)
        at d.a.j.b.a(PublishSubject.java:15)
        at h.c.e.b.a(Dispatcher.kt:2)
        at h.c.g._a.accept(ItemListPresenter.kt:4)
        at d.a.e.d.g.a(LambdaObserver.java:7)
        at d.a.e.d.f.a(DisposableLambdaObserver.java:9)
        at d.a.e.e.b.p$a.a(ObservableMap.java:5)
        at b.w.a.e.onAnimationEnd(SwipeRefreshLayout.java:20)
        at b.w.a.a.onAnimationEnd(CircleImageView.java:3)
        at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:7288)
        at android.view.View.draw(View.java:21786)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:16)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.View.draw(View.java:21608)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4553)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4328)
        at android.view.View.draw(View.java:21885)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1082)
        at android.view.View.updateDisplayListIfDirty(View.java:20755)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
2019-07-29 15:40:45.723 29338-29338/? E/AndroidRuntime:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3912)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3686)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2994)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1853)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8476)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: f.c
        at h.c.h.F.e(DataStore.kt:13)
        at h.c.h.F.l(DataStore.kt:1)
        at h.c.h.B.accept(DataStore.kt:4)
        at d.a.e.d.g.a(LambdaObserver.java:7)
        	... 83 more
```

**Comment by eliserichards** [comment]
Parent issue to handle network connectivity improvements: #373
