### ISSUE TITLE
App crashes upon startup

### ISSUE THREAD

**Issue by verwinv** [mozilla-lockwise/lockwise-android#878]
Using Lockwise on Android version 9, EMUI version 9.0.0 on a CLT-L09 Huawei phone. As of a few days (haven't recorded when precisely) the app no longer opens - password suggestions in Firefox seem to work fine, but opening the app itself only brings up the splash screen, which then disappears from view.

**Comment by jhugman** [comment]
Thanks for your report. 

Are you able to capture the `logcat` of your session?

We do have crash logs, but it would be good to be able to isolate your particular problem to identify which of the crashes will mostly affect you. 

Many thanks,

**Comment by iTiPo** [comment]
```
--------- beginning of crash
08-18 20:24:07.608  3741  3834 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
08-18 20:24:07.608  3741  3834 E AndroidRuntime: Process: mozilla.lockbox, PID: 3741
08-18 20:24:07.608  3741  3834 E AndroidRuntime: d.a.c.b: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | null
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.b.a$l.accept(Functions.java:2)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.d.g.a(LambdaObserver.java:13)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.d.g.a(LambdaObserver.java:10)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at c.g.b.d$d.a(ReplayRelay.java:21)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at c.g.b.d.accept(ReplayRelay.java:4)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at h.c.h.aa.a(DataStore.kt:3)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at h.c.h.Q.accept(Unknown Source:2)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.d.g.a(LambdaObserver.java:7)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.e.b.p$a.a(ObservableMap.java:5)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.e.b.y$a.a(ObservableTake.java:10)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.e.b.w$a.a(ObservableSkip.java:6)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.e.b.g$a.a(ObservableDoOnEach.java:6)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.e.b.x$b.e(ObservableSwitchMap.java:36)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.e.b.x$a.a(ObservableSwitchMap.java:12)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at c.g.b.b$a.a(BehaviorRelay.java:44)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at c.g.b.b.accept(BehaviorRelay.java:6)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at h.c.h.ca.accept(DataStore.kt:2)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.d.d.b(ConsumerSingleObserver.java:2)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at g.b.c.f.h(RxSingle.kt:8)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at g.b.a.e(AbstractCoroutine.kt:5)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at g.b.na.a(JobSupport.kt:95)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at g.b.a.b(AbstractCoroutine.kt:3)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at f.b.b.a.a.b(ContinuationImpl.kt:8)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at g.b.S.run(Dispatched.kt:15)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at g.b.d.b.a(CoroutineScheduler.kt:31)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at g.b.d.b.a(CoroutineScheduler.kt:23)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at g.b.d.b$a.run(CoroutineScheduler.kt:42)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: Caused by: f.c
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at h.c.h.F.e(DataStore.kt:13)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at h.c.h.F.m(DataStore.kt:4)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at h.c.h.A.accept(DataStore.kt:3)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	at d.a.e.d.g.a(LambdaObserver.java:7)
08-18 20:24:07.608  3741  3834 E AndroidRuntime: 	... 24 more
```

**Comment by verwinv** [comment]
Hi, sorry for the delay - hadn't heard of a logcat before. See the attached for the about 6 seconds of logcat output after opening the Lockwise app on my device. 
[2019-08-18_logcat.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3513362/2019-08-18_logcat.txt)

**Comment by krzyk** [comment]
Same happens on a pixel 3, app version 1.1.3.
And the app crash dialog  appears on almost every dialog input field in Android, bcery annoying. I sent several issue reports from Android crash reporter.
