### ISSUE TITLE
[UITests] Fix failing UITests after recent commits

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#907]
### Vision statement / What / Requirements
Latest scheduled build on [Bitrise](https://app.bitrise.io/build/94f9d6550c714f5a#?tab=log) is failing due to [two tests](https://addons-testing.bitrise.io/builds/94f9d6550c714f5a/testreport/ftl/testsuite/0/testcases?status=failed):
-testSettings
-testDisconnectDisclaimer

PR with a fix coming soon

**Comment by isabelrios** [comment]
So after the failure in `testDisconnectDisclaimer`no more tests are executed.
The failure is:
```
Cannot route from mozilla.lockbox:id/fragment_null to mozilla.lockbox:id/fragment_setting. This is a developer bug, fixable by adding an action to mozilla.lockbox:id/graph_main.xml and/or AppRoutePresenter
at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
at io.reactivex.internal.observers.LambdaOb
....
```
