### ISSUE TITLE
Tapping on the X button when in Error state causes crash

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#982]
## Steps to reproduce
1. Launch Lockwise.
2. Login with valid credentials.
3. Access any account.
4. Tap on 3 dot menu and enter the Edit Login mode.
5. Tap back(on the device button or Lockwise button).
6. Tap on the `X` button.
### Expected behavior
The edit mode is closed and the account information is displayed.
### Actual behavior
Lockwise crashes when tapping on the `X` button.
### Device & build information
* Device: Google Pixel 3a XL(Android 9)
* Build version: Latest build from master(17/10/2019)
### Notes
Attachments: 
[Video](https://drive.google.com/file/d/1uGAJi0OrcdqMSDSZRHLNqvjSvSzV2iXZ/view?usp=sharing)

**Comment by abodea** [comment]
```Kotlin
 --------- beginning of crash
2019-10-17 13:06:25.732 13449-13449/mozilla.lockbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mozilla.lockbox, PID: 13449
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | null
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at com.jakewharton.rxbinding2.support.v7.widget.ToolbarNavigationClickObservable$Listener.onClick(ToolbarNavigationClickObservable.java:39)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.KotlinNullPointerException
        at mozilla.lockbox.presenter.EditItemPresenter$onViewReady$8.accept(EditItemPresenter.kt:108)
        at mozilla.lockbox.presenter.EditItemPresenter$onViewReady$8.accept(EditItemPresenter.kt:49)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62) 
        at com.jakewharton.rxbinding2.support.v7.widget.ToolbarNavigationClickObservable$Listener.onClick(ToolbarNavigationClickObservable.java:39) 
        at android.view.View.performClick(View.java:6597) 
        at android.view.View.performClickInternal(View.java:6574) 
        at android.view.View.access$3100(View.java:778) 
        at android.view.View$PerformClick.run(View.java:25885) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by abodea** [comment]
I believe it's happening because of [`Error Handling` ](https://github.com/ReactiveX/RxJava/wiki/Error-Handling)
here are some exceptions to this. For example, if the onError() call itself fails, the Observable will not attempt to notify the observer of this by again calling onError but will throw a RuntimeException, an OnErrorFailedException, or an OnErrorNotImplementedException.

**Comment by jhugman** [comment]
The line is instructive here:

```stacktrace
at mozilla.lockbox.presenter.EditItemPresenter$onViewReady$8.accept(EditItemPresenter.kt:108)
```

**Comment by jhugman** [comment]
This was fixed as [part of #990][1], and became Impossible To Reproduce™ with #993.

@abodea could you retest?

[1]: https://github.com/mozilla-lockwise/lockwise-android/pull/990/files#diff-bb765cf5213807ff6b24b1ab1562344cR108

**Comment by isabelrios** [comment]
Thanks for the fix! I can't reproduce this anymore... :)

**Comment by jhugman** [comment]
🤜  🤛 Thanks, @isabelrios
